name: man utd Script

on:
  schedule:
    - cron: '0 * * * *'   # every hour on the hour
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      # -------------------------------------------------
      # 1. Get UTC hour and decide whether to run
      # -------------------------------------------------
      - name: Check allowed hour (12-23 UTC)
        id: hour_check
        run: |
          H=$(date -u +%H)
          echo "Current UTC hour: $H"
          echo "hour=$H" >> $GITHUB_OUTPUT
          if (( H >= 12 )); then
            echo "run_job=true" >> $GITHUB_OUTPUT
          else
            echo "run_job=false" >> $GITHUB_OUTPUT
          fi

      # -------------------------------------------------
      # 2. All real work – only when run_job == true
      # -------------------------------------------------
      - name: Checkout repository
        if: ${{ steps.hour_check.outputs.run_job == 'true' }}
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        if: ${{ steps.hour_check.outputs.run_job == 'true' }}
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        if: ${{ steps.hour_check.outputs.run_job == 'true' }}
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 pandas numpy

      - name: Run script
        if: ${{ steps.hour_check.outputs.run_job == 'true' }}
        run: python manutd.py

      - name: List files for debugging
        if: ${{ steps.hour_check.outputs.run_job == 'true' }}
        run: |
          echo "Current directory: $(pwd)"
          ls -l

      - name: Commit and push changes if any
        if: ${{ steps.hour_check.outputs.run_job == 'true' }}
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "Automated update: $(date +'%Y-%m-%d %H:%M:%S')"
            git push
          else
            echo "No changes to commit"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
