name: staðfangaskrá

on:
  schedule:
    - cron: '0 0 * * 0'  # Runs every Sunday at 00:00 UTC
  workflow_dispatch:  # Allows manual triggering from the GitHub UI

jobs:
  process:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install pandas

      - name: Run processing script
        run: python stadfangaskra.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git pull origin main --rebase
          git add stadfangaskra_trimmed.csv icelandic_addresses.csv || true
          git commit -m "Weekly update: Processed Icelandic addresses" || echo "No changes to commit"
          git push origin main || echo "No changes to push"
